-- ============================================================
-- CIVICMARKET SCHEMA ADDENDUM — PROFILES COLUMN-LEVEL UPDATE GRANTS
--
-- ALREADY RUN manually in the Supabase SQL Editor on 2026-09-13.
-- This file records a change that was made in the dashboard, so schema
-- history is complete. It is not pending work.
--
-- WHY THIS EXISTS
-- Production had column-level UPDATE grants on `profiles` that appear in
-- no migration file — dashboard drift. Four columns the app writes were
-- missing from those grants, so PostgREST rejected any PATCH naming them
-- with 403 Forbidden:
--
--   display_name              (comments, screen 4 — how this was found)
--   top_issues                (onboarding /issues, screen 1)
--   onboarding_completed_at   (onboarding /issues, screen 1)
--   address_validation_source (onboarding /verify, screen 1)
--
-- Row-level security was never the problem. The self-update policy in
-- civicmarket_schema_v4.sql is correct and unchanged. RLS decides WHICH
-- ROW a user may write; column privileges decide WHICH COLUMNS. Only the
-- second was wrong.
--
-- HOW LONG IT WAS BROKEN
-- Silently, since the top_issues migration. Every existing caller
-- console.errors the failure and navigates on regardless
-- (src/app/onboarding/issues/page.tsx, .../zip/page.tsx,
-- .../verify/page.tsx), so three onboarding writes were failing with no
-- visible symptom. src/lib/comments.ts is the first caller that throws,
-- which is the only reason this surfaced.
--
-- Any account that finished onboarding before 2026-09-13 may therefore
-- have NULL top_issues and NULL onboarding_completed_at. The comments
-- INSERT policy requires onboarding_completed_at IS NOT NULL, so those
-- accounts cannot comment until they redo the /issues step or the column
-- is backfilled.
-- ============================================================

-- ============================================================
-- SECTION 1: THE GRANT THAT WAS RUN
--
-- Additive only. There is deliberately no REVOKE here: the pre-existing
-- grant list is not recorded anywhere in this repo, and revoking to a
-- list reconstructed from guesswork would break writes that currently
-- work. Safe to re-run.
-- ============================================================

GRANT UPDATE (
  display_name,
  top_issues,
  onboarding_completed_at,
  address_validation_source
) ON profiles TO authenticated;

-- ============================================================
-- SECTION 2: KNOWN GAP — THE FULL GRANT LIST IS STILL NOT IN THE REPO
--
-- This file records the delta that was applied, not the complete
-- privilege state of `profiles`. The rest of that state exists only in
-- the database. Until it is dumped and committed, a fresh environment
-- built from supabase/migrations/ will NOT match production.
--
-- To capture it:
--
--   SELECT grantee, privilege_type, column_name
--     FROM information_schema.column_privileges
--    WHERE table_name = 'profiles'
--      AND grantee IN ('anon', 'authenticated')
--    ORDER BY grantee, privilege_type, column_name;
--
-- Columns that must NEVER appear in an UPDATE grant to `authenticated`:
--
--   is_admin                     privilege escalation — grants the
--                                comment-hide power in screen 4
--   banned_at, ban_reason,
--   warned_at                    moderation state; a banned user could
--                                unban themselves
--   verification_tier,
--   address_verified,
--   address_validated_at,
--   voter_roll_verified_at,
--   phone_verified_at,
--   phone_number_e164            attestations that a check was performed.
--                                Self-writable, they become claims the
--                                product does not actually perform
--   civic_points, civic_level    reputation. CIVIC_REPUTATION_SPEC.md
--                                sections 2 and 4 tie both to adjudicated
--                                events, never to self-report
--   district_id                  district assignment belongs to the ZIP
--                                flow and the guarded RPC
--   tos_agreed_at, tos_version   legal attestation
--   id, created_at               identity and audit
--
-- If the dump shows any of the above granted, revoke it.
-- ============================================================
